# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160408_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rvoption',
            name='response',
        ),
        migrations.RemoveField(
            model_name='tvoption',
            name='thread',
        ),
    ]
