# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160408_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvote',
            name='option',
            field=models.CharField(choices=[('SE', 'SuperElf'), ('VU', 'VeryUseful'), ('LV', 'LoveThis'), ('IA', 'IAgree'), ('MS', 'MySympathies'), ('OT', 'OffTopic'), ('TR', 'Troll')], max_length=2),
        ),
    ]
