# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160420_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvote',
            old_name='thread',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='tvote',
            unique_together=set([('post', 'user')]),
        ),
    ]
