# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160420_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rvote',
            old_name='response',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='rvote',
            unique_together=set([('post', 'user')]),
        ),
    ]
