# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160503_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvote',
            name='option',
            field=models.CharField(choices=[('TR', 'Troll'), ('SE', 'SuperElf')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tvote',
            name='option',
            field=models.CharField(choices=[('TR', 'Troll'), ('SE', 'SuperElf')], max_length=2),
        ),
    ]
