# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 23:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160906_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_thread',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 6, 23, 47, 57, 63172, tzinfo=utc)),
        ),
    ]
