# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160906_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='tvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
