# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_thread_tvote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='rvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
