# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160913_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='vote_count',
            new_name='rvote_count',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='vote_count',
            new_name='tvote_count',
        ),
    ]
