# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20160913_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='vote_count',
        ),
    ]
