# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20160913_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
