# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_userprofile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
    ]
