# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-28 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20160918_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RVOption',
        ),
        migrations.DeleteModel(
            name='TVOption',
        ),
    ]
