# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-28 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20160928_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_thread',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
