# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-30 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20160928_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_thread',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 29, 0, 24, 8, 9112, tzinfo=utc)),
        ),
    ]
