# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-01 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20160929_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='curr_thread',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_thread',
        ),
    ]
