# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-01 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20161001_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
