# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_response_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
