# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-12 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20161012_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='activity_rvotes',
            new_name='activity_votes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_tvotes',
        ),
    ]
