# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-13 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20161012_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='vote_count',
        ),
    ]
