# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20161013_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
