# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20161018_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_thread',
            new_name='origin_date',
        ),
    ]
