# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20161018_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity_responses',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_threads',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_votes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
