# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20161018_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='origin_date',
            field=models.DateTimeField(null=True),
        ),
    ]
