# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20161019_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='troll_check',
            field=models.DateTimeField(null=True),
        ),
    ]
