# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-31 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_userprofile_troll_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_responses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_threads',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_votes',
        ),
    ]
